### PR TITLE
Remove unnecessary files from npm package

### PR DESCRIPTION
**Pull request by jorrit**

### CODE REVIEW

**Comment by moll** [comment]
Hey,

Why do you consider the CHANGELOG et alii to be unnecessary? Distributing tests along with the source code permits people to optionally run tests before installing — and therefore also requires the `Makefile`. The CHANGELOG permits them, when upgrading, to understand what has changed.

**Comment by jorrit** [comment]
I see your point. I think most people will consult GitHub for those purposes. Testing modules from within your node_modules seems a bit unusual to me, because it would also require you to run `npm install` from within `node_modules/fetch-error` to get the devDependencies. A clean git checkout is much more suitable for that. Do you often test modules inside the node_modules folder of your applications or libraries?

**Comment by moll** [comment]
I don't personally do it often, but I like to provide the possibility for those in need. Some package managers, like Perl's CPAN, for example, run all tests every time they install a package. I also think the packaged module should really contain nearly everything available in the repository for longevity and for people that can't access the repository. You might've heard US has required Microsoft and thereby GitHub to discriminate based on either nationality or country of origin, blocking access to more than a few countries around the world. For those people, NPM may be the only path to a module's tests, CHANGELOG and other auxiliary files.

**Comment by jorrit** [comment]
I hadn't thought of that. I have updated the PR to only remove the npm ignore fle itself, but feel free to close this PR without merging.

**Comment by moll** [comment]
There was a time when I ignored `.npmignore` itself, too. :P Once I came upon the nearly-everything-in-the-distribution principle, however, I left it in. Namely, to help those who want to publish the package fresh from the unpacked module. In practice, though, I tend to just ignore tarballs with it, because as far as I konw, NPM lacks a global ignore file and without a local one, I often accidentally include the result of a previous `npm pack` — the module tarball.

So if you don't mind, I wouldn't ignore `.npmignore` either. :)

**Comment by moll** [comment]
I'll close the PR for you, though we're welcome to continue chatting. ;)

**Pull request closed without merging**
